<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Operations;

use \structure\Structure\Utils\SpeakeasyMetadata;
class CompanyEmployeesPathParams
{
    /**
     * ID of the company
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->id = "";
	}
}
