<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Operations;


class CompanyJobsRequest
{
	
    public CompanyJobsPathParams $pathParams;
    
	
    public CompanyJobsQueryParams $queryParams;
    
	public function __construct()
	{
		$this->pathParams = new \structure\Structure\Models\Operations\CompanyJobsPathParams();
		$this->queryParams = new \structure\Structure\Models\Operations\CompanyJobsQueryParams();
	}
}
