<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Operations;


class CompanyEmployeesRequest
{
	
    public CompanyEmployeesPathParams $pathParams;
    
	
    public CompanyEmployeesQueryParams $queryParams;
    
	public function __construct()
	{
		$this->pathParams = new \structure\Structure\Models\Operations\CompanyEmployeesPathParams();
		$this->queryParams = new \structure\Structure\Models\Operations\CompanyEmployeesQueryParams();
	}
}
