<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Operations;

use \structure\Structure\Utils\SpeakeasyMetadata;
class CompanyEmployeesQueryParams
{
    /**
     * The offset number to start at
     * 
     * @var ?string $offset
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=offset')]
    public ?string $offset = null;
    
    /**
     * Number of results per page (0-100)
     * 
     * @var ?string $perPage
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=per_page')]
    public ?string $perPage = null;
    
	public function __construct()
	{
		$this->offset = null;
		$this->perPage = null;
	}
}
