<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Operations;


class EnrichPersonRequest
{
	
    public EnrichPersonQueryParams $queryParams;
    
	public function __construct()
	{
		$this->queryParams = new \structure\Structure\Models\Operations\EnrichPersonQueryParams();
	}
}
