<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Operations;

use \structure\Structure\Utils\SpeakeasyMetadata;
class SearchSearchRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public mixed $request = null;
    
	public function __construct()
	{
		$this->request = null;
	}
}
