<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\structure\Models\Shared;


class Account
{
    /**
     * List of the users in the account
     * 
     * @var array<string> $accountUsers
     */
	
    public array $accountUsers;
    
    /**
     * Timestamp of the account creation date
     * 
     * @var string $createdAt
     */
	
    public string $createdAt;
    
    /**
     * The id of the account
     * 
     * @var float $id
     */
	
    public float $id;
    
    /**
     * The name of the account
     * 
     * @var string $name
     */
	
    public string $name;
    
    /**
     * The id of the account owner
     * 
     * @var float $ownerId
     */
	
    public float $ownerId;
    
    /**
     * If the account is personal or belonging to another account
     * 
     * @var bool $personal
     */
	
    public bool $personal;
    
    /**
     * Timestamp of the last account update date
     * 
     * @var string $updatedAt
     */
	
    public string $updatedAt;
    
	public function __construct()
	{
		$this->accountUsers = [];
		$this->createdAt = "";
		$this->id = 0;
		$this->name = "";
		$this->ownerId = 0;
		$this->personal = false;
		$this->updatedAt = "";
	}
}
