<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Shared;


/**
 * Company - returns the company
 * 
 * @package structure\Structure\Models\Shared
 * @access public
 */
class Company
{
    /**
     * The company's description
     * 
     * @var string $about
     */
	
    public string $about;
    
    /**
     * Affiliated companies to the company
     * 
     * @var array<string> $affiliated
     */
	
    public array $affiliated;
    
    /**
     * The size of the company
     * 
     * @var string $companySize
     */
	
    public string $companySize;
    
    /**
     * The country's country code
     * 
     * @var string $countryCode
     */
	
    public string $countryCode;
    
    /**
     * A sample of the company's employees. See the employees endpoint for the full list.
     * 
     * @var array<string> $employees
     */
	
    public array $employees;
    
    /**
     * The number of company employees on LinkedIn
     * 
     * @var float $employeesInLinkedin
     */
	
    public float $employeesInLinkedin;
    
    /**
     * The number of company followers on LinkedIn
     * 
     * @var float $followers
     */
	
    public float $followers;
    
    /**
     * The year the company was founded
     * 
     * @var float $founded
     */
	
    public float $founded;
    
    /**
     * The funding status of the company
     * 
     * @var string $funding
     */
	
    public string $funding;
    
    /**
     * The country's headquarters
     * 
     * @var string $headquarters
     */
	
    public string $headquarters;
    
    /**
     * The key for looking up the company
     * 
     * @var float $id
     */
	
    public float $id;
    
    /**
     * The company's industries
     * 
     * @var string $industries
     */
	
    public string $industries;
    
    /**
     * The company's investors
     * 
     * @var string $investors
     */
	
    public string $investors;
    
    /**
     * Sample of company's Jobs. See the jobs endpoint for the full list.
     * 
     * @var array<string> $jobs
     */
	
    public array $jobs;
    
    /**
     * The company's LinkedIn ID
     * 
     * @var string $lid
     */
	
    public string $lid;
    
    /**
     * The company's locations
     * 
     * @var array<string> $locations
     */
	
    public array $locations;
    
    /**
     * URL to the company's logo
     * 
     * @var string $logo
     */
	
    public string $logo;
    
    /**
     * The company's name
     * 
     * @var string $name
     */
	
    public string $name;
    
    /**
     * The type of organization
     * 
     * @var string $organizationType
     */
	
    public string $organizationType;
    
    /**
     * The comapny's headquarters region
     * 
     * @var string $region
     */
	
    public string $region;
    
    /**
     * Similar companies to this company
     * 
     * @var array<string> $similar
     */
	
    public array $similar;
    
    /**
     * The company's slogan
     * 
     * @var string $slogan
     */
	
    public string $slogan;
    
    /**
     * The company's specialities
     * 
     * @var string $specialities
     */
	
    public string $specialities;
    
    /**
     * The company's sphere of products
     * 
     * @var string $sphere
     */
	
    public string $sphere;
    
    /**
     * The type of company (public, private, etc.)
     * 
     * @var string $type
     */
	
    public string $type;
    
    /**
     * The company's linkedIn URL
     * 
     * @var string $url
     */
	
    public string $url;
    
    /**
     * The company's website
     * 
     * @var string $website
     */
	
    public string $website;
    
	public function __construct()
	{
		$this->about = "";
		$this->affiliated = [];
		$this->companySize = "";
		$this->countryCode = "";
		$this->employees = [];
		$this->employeesInLinkedin = 0;
		$this->followers = 0;
		$this->founded = 0;
		$this->funding = "";
		$this->headquarters = "";
		$this->id = 0;
		$this->industries = "";
		$this->investors = "";
		$this->jobs = [];
		$this->lid = "";
		$this->locations = [];
		$this->logo = "";
		$this->name = "";
		$this->organizationType = "";
		$this->region = "";
		$this->similar = [];
		$this->slogan = "";
		$this->specialities = "";
		$this->sphere = "";
		$this->type = "";
		$this->url = "";
		$this->website = "";
	}
}
