<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\structure\Models\Shared;


/**
 * Person - returns the person
 * 
 * @package structure\structure\Models\Shared
 * @access public
 */
class Person
{
    /**
     * The birth date of the person
     * 
     * @var string $birthDate
     */
	
    public string $birthDate;
    
    /**
     * The birth year of the person
     * 
     * @var float $birthYear
     */
	
    public float $birthYear;
    
    /**
     * The certifications of the person
     * 
     * @var array<string> $certifications
     */
	
    public array $certifications;
    
    /**
     * The educational history of the person
     * 
     * @var array<string> $education
     */
	
    public array $education;
    
    /**
     * The personal and work emails of the person
     * 
     * @var array<string> $emails
     */
	
    public array $emails;
    
    /**
     * The works experience of the person
     * 
     * @var array<string> $experience
     */
	
    public array $experience;
    
    /**
     * The Facebook ID of the person
     * 
     * @var string $facebookId
     */
	
    public string $facebookId;
    
    /**
     * The Facebook URL of the person
     * 
     * @var string $facebookUrl
     */
	
    public string $facebookUrl;
    
    /**
     * The Facebook username of the person
     * 
     * @var string $facebookUsername
     */
	
    public string $facebookUsername;
    
    /**
     * The first name of the person
     * 
     * @var string $firstName
     */
	
    public string $firstName;
    
    /**
     * The full name of the person
     * 
     * @var string $fullName
     */
	
    public string $fullName;
    
    /**
     * The gender of the person
     * 
     * @var string $gender
     */
	
    public string $gender;
    
    /**
     * The Github URL of the person
     * 
     * @var string $githubUrl
     */
	
    public string $githubUrl;
    
    /**
     * The Github username of the person
     * 
     * @var string $githubUsername
     */
	
    public string $githubUsername;
    
    /**
     * The key for looking up the company
     * 
     * @var float $id
     */
	
    public float $id;
    
    /**
     * The industry of the person
     * 
     * @var string $industry
     */
	
    public string $industry;
    
    /**
     * The inferred salary band for the person
     * 
     * @var string $inferredSalary
     */
	
    public string $inferredSalary;
    
    /**
     * The inferred years of experience for the person
     * 
     * @var float $inferredYearsExperience
     */
	
    public float $inferredYearsExperience;
    
    /**
     * The interests of the person
     * 
     * @var array<string> $interests
     */
	
    public array $interests;
    
    /**
     * The current job company Facebook URL
     * 
     * @var string $jobCompanyFacebookUrl
     */
	
    public string $jobCompanyFacebookUrl;
    
    /**
     * The current job company founded year
     * 
     * @var string $jobCompanyFounded
     */
	
    public string $jobCompanyFounded;
    
    /**
     * The current job company ID
     * 
     * @var string $jobCompanyId
     */
	
    public string $jobCompanyId;
    
    /**
     * The current job company industry
     * 
     * @var string $jobCompanyIndustry
     */
	
    public string $jobCompanyIndustry;
    
    /**
     * The current job company id on LinkedIn
     * 
     * @var string $jobCompanyLinkedinId
     */
	
    public string $jobCompanyLinkedinId;
    
    /**
     * The current job company LinkedIn URL
     * 
     * @var string $jobCompanyLinkedinUrl
     */
	
    public string $jobCompanyLinkedinUrl;
    
    /**
     * The current job company location street adress second line
     * 
     * @var string $jobCompanyLocationAddressLine2
     */
	
    public string $jobCompanyLocationAddressLine2;
    
    /**
     * The current job company location continent
     * 
     * @var string $jobCompanyLocationContinent
     */
	
    public string $jobCompanyLocationContinent;
    
    /**
     * The current job company location country
     * 
     * @var string $jobCompanyLocationCountry
     */
	
    public string $jobCompanyLocationCountry;
    
    /**
     * The current job company location geo coordinates
     * 
     * @var string $jobCompanyLocationGeo
     */
	
    public string $jobCompanyLocationGeo;
    
    /**
     * The current job company location city
     * 
     * @var string $jobCompanyLocationLocality
     */
	
    public string $jobCompanyLocationLocality;
    
    /**
     * The current job company location metro
     * 
     * @var string $jobCompanyLocationMetro
     */
	
    public string $jobCompanyLocationMetro;
    
    /**
     * The current job company location name
     * 
     * @var string $jobCompanyLocationName
     */
	
    public string $jobCompanyLocationName;
    
    /**
     * The current job company location postal code
     * 
     * @var string $jobCompanyLocationPostalCode
     */
	
    public string $jobCompanyLocationPostalCode;
    
    /**
     * The current job company location region
     * 
     * @var string $jobCompanyLocationRegion
     */
	
    public string $jobCompanyLocationRegion;
    
    /**
     * The current job company location street address
     * 
     * @var string $jobCompanyLocationStreetAddress
     */
	
    public string $jobCompanyLocationStreetAddress;
    
    /**
     * The current job company name
     * 
     * @var string $jobCompanyName
     */
	
    public string $jobCompanyName;
    
    /**
     * The current job company size
     * 
     * @var string $jobCompanySize
     */
	
    public string $jobCompanySize;
    
    /**
     * The current job company Twitter URL
     * 
     * @var string $jobCompanyTwitterUrl
     */
	
    public string $jobCompanyTwitterUrl;
    
    /**
     * The current job company website
     * 
     * @var string $jobCompanyWebsite
     */
	
    public string $jobCompanyWebsite;
    
    /**
     * The last update date for the job
     * 
     * @var string $jobLastUpdated
     */
	
    public string $jobLastUpdated;
    
    /**
     * The start date for the current job
     * 
     * @var string $jobStartDate
     */
	
    public string $jobStartDate;
    
    /**
     * The summary for the current job
     * 
     * @var string $jobSummary
     */
	
    public string $jobSummary;
    
    /**
     * The current job title of the person
     * 
     * @var string $jobTitle
     */
	
    public string $jobTitle;
    
    /**
     * The current job title levels
     * 
     * @var array<string> $jobTitleLevels
     */
	
    public array $jobTitleLevels;
    
    /**
     * The current job title role of the person
     * 
     * @var string $jobTitleRole
     */
	
    public string $jobTitleRole;
    
    /**
     * The current job title sub-role of the person
     * 
     * @var string $jobTitleSubRole
     */
	
    public string $jobTitleSubRole;
    
    /**
     * The languages of the person
     * 
     * @var array<string> $languages
     */
	
    public array $languages;
    
    /**
     * The last name of the person
     * 
     * @var string $lastName
     */
	
    public string $lastName;
    
    /**
     * The number of LinkedIn connections for the person
     * 
     * @var float $linkedinConnections
     */
	
    public float $linkedinConnections;
    
    /**
     * The linkedIn ID of the person
     * 
     * @var float $linkedinId
     */
	
    public float $linkedinId;
    
    /**
     * The linkedIn URL of the person
     * 
     * @var string $linkedinUrl
     */
	
    public string $linkedinUrl;
    
    /**
     * The linkedIn user name of the person
     * 
     * @var string $linkedinUsername
     */
	
    public string $linkedinUsername;
    
    /**
     * The current location street address second line for the person
     * 
     * @var string $locationAddressLineTwo
     */
	
    public string $locationAddressLineTwo;
    
    /**
     * The current location continent for the person
     * 
     * @var string $locationContinent
     */
	
    public string $locationContinent;
    
    /**
     * The current location country for the person
     * 
     * @var string $locationCountry
     */
	
    public string $locationCountry;
    
    /**
     * The current location geo coordinates for the person
     * 
     * @var array<string> $locationGeo
     */
	
    public array $locationGeo;
    
    /**
     * The current location last updated date for the person
     * 
     * @var string $locationLastUpdated
     */
	
    public string $locationLastUpdated;
    
    /**
     * The current location city for the person
     * 
     * @var string $locationLocality
     */
	
    public string $locationLocality;
    
    /**
     * The current location metro for the person
     * 
     * @var string $locationMetro
     */
	
    public string $locationMetro;
    
    /**
     * The current location name for the person
     * 
     * @var string $locationName
     */
	
    public string $locationName;
    
    /**
     * The current location postal code for the person
     * 
     * @var string $locationPostalCode
     */
	
    public string $locationPostalCode;
    
    /**
     * The current location region for the person
     * 
     * @var string $locationRegion
     */
	
    public string $locationRegion;
    
    /**
     * The current location street address for the person
     * 
     * @var string $locationStreetAddress
     */
	
    public string $locationStreetAddress;
    
    /**
     * The middle initial of the person
     * 
     * @var string $middleInitial
     */
	
    public string $middleInitial;
    
    /**
     * The middle name of the person
     * 
     * @var string $middleName
     */
	
    public string $middleName;
    
    /**
     * The mobile phone of the person
     * 
     * @var string $mobilePhone
     */
	
    public string $mobilePhone;
    
    /**
     * The phone numbers of the person
     * 
     * @var array<string> $phoneNumbers
     */
	
    public array $phoneNumbers;
    
    /**
     * The social profiles of the person
     * 
     * @var array<string> $profiles
     */
	
    public array $profiles;
    
    /**
     * The skills of the person
     * 
     * @var array<string> $skills
     */
	
    public array $skills;
    
    /**
     * The street addresses of the person
     * 
     * @var array<string> $streetAddresses
     */
	
    public array $streetAddresses;
    
    /**
     * The self-summary of the person's work experience
     * 
     * @var string $summary
     */
	
    public string $summary;
    
    /**
     * The Twitter URL of the person
     * 
     * @var string $twitterUrl
     */
	
    public string $twitterUrl;
    
    /**
     * The Twitter username of the person
     * 
     * @var string $twitterUsername
     */
	
    public string $twitterUsername;
    
    /**
     * The work email of the person
     * 
     * @var string $workEmail
     */
	
    public string $workEmail;
    
	public function __construct()
	{
		$this->birthDate = "";
		$this->birthYear = 0;
		$this->certifications = [];
		$this->education = [];
		$this->emails = [];
		$this->experience = [];
		$this->facebookId = "";
		$this->facebookUrl = "";
		$this->facebookUsername = "";
		$this->firstName = "";
		$this->fullName = "";
		$this->gender = "";
		$this->githubUrl = "";
		$this->githubUsername = "";
		$this->id = 0;
		$this->industry = "";
		$this->inferredSalary = "";
		$this->inferredYearsExperience = 0;
		$this->interests = [];
		$this->jobCompanyFacebookUrl = "";
		$this->jobCompanyFounded = "";
		$this->jobCompanyId = "";
		$this->jobCompanyIndustry = "";
		$this->jobCompanyLinkedinId = "";
		$this->jobCompanyLinkedinUrl = "";
		$this->jobCompanyLocationAddressLine2 = "";
		$this->jobCompanyLocationContinent = "";
		$this->jobCompanyLocationCountry = "";
		$this->jobCompanyLocationGeo = "";
		$this->jobCompanyLocationLocality = "";
		$this->jobCompanyLocationMetro = "";
		$this->jobCompanyLocationName = "";
		$this->jobCompanyLocationPostalCode = "";
		$this->jobCompanyLocationRegion = "";
		$this->jobCompanyLocationStreetAddress = "";
		$this->jobCompanyName = "";
		$this->jobCompanySize = "";
		$this->jobCompanyTwitterUrl = "";
		$this->jobCompanyWebsite = "";
		$this->jobLastUpdated = "";
		$this->jobStartDate = "";
		$this->jobSummary = "";
		$this->jobTitle = "";
		$this->jobTitleLevels = [];
		$this->jobTitleRole = "";
		$this->jobTitleSubRole = "";
		$this->languages = [];
		$this->lastName = "";
		$this->linkedinConnections = 0;
		$this->linkedinId = 0;
		$this->linkedinUrl = "";
		$this->linkedinUsername = "";
		$this->locationAddressLineTwo = "";
		$this->locationContinent = "";
		$this->locationCountry = "";
		$this->locationGeo = [];
		$this->locationLastUpdated = "";
		$this->locationLocality = "";
		$this->locationMetro = "";
		$this->locationName = "";
		$this->locationPostalCode = "";
		$this->locationRegion = "";
		$this->locationStreetAddress = "";
		$this->middleInitial = "";
		$this->middleName = "";
		$this->mobilePhone = "";
		$this->phoneNumbers = [];
		$this->profiles = [];
		$this->skills = [];
		$this->streetAddresses = [];
		$this->summary = "";
		$this->twitterUrl = "";
		$this->twitterUsername = "";
		$this->workEmail = "";
	}
}
