<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace structure\Structure\Models\Shared;

use \structure\Structure\Utils\SpeakeasyMetadata;
class Security
{
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer')]
    public SchemeBearerAuth $bearerAuth;
    
	public function __construct()
	{
		$this->bearerAuth = new \structure\Structure\Models\Shared\SchemeBearerAuth();
	}
}
